GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY2ODRjMDdlMzVkMTdiYTUwOTc2ZWIiLCJ1c2VybmFtZSI6ImFsYmluc3VwZXJhZG1pbiIsImVtYWlsIjoiYWxiaW5zdXBlcmFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJzdXBlcmFkbWluIiwiY3JlYXRlZEF0IjoiMjAyMi0wMS0zMFQxMjoyOTo1Mi4yMDVaIiwiaWF0IjoxNjQzNzM4ODQ2LCJleHAiOjE2NDM3NDA2NDZ9.HcqRTN5ud_nrxTXEnTL5L5uRTSCcEeA1zg40si7Yqro

###

GET http://localhost:5000/users/61f684a37e35d17ba50976e6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY2ODRjMDdlMzVkMTdiYTUwOTc2ZWIiLCJ1c2VybmFtZSI6ImFsYmluc3VwZXJhZG1pbiIsImVtYWlsIjoiYWxiaW5zdXBlcmFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJzdXBlcmFkbWluIiwiY3JlYXRlZEF0IjoiMjAyMi0wMS0zMFQxMjoyOTo1Mi4yMDVaIiwiaWF0IjoxNjQzNzMwNzg2LCJleHAiOjE2NDM3MzI1ODZ9.lp6xA-KZq60uEdfwd-GQS5-NPGXUrkcTNb8rZUDRM-8

###

PATCH http://localhost:5000/users/61f97765b43515ed7b76872b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY5Nzc2NWI0MzUxNWVkN2I3Njg3MmIiLCJ1c2VybmFtZSI6ImFsYmluc3VwZXJhZG1pbiIsImVtYWlsIjoiYWxiaW5zdXBlcmFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJzdXBlcmFkbWluIiwiY3JlYXRlZEF0IjoiMjAyMi0wMi0wMVQxODowOTo0MS43NTdaIiwiaWF0IjoxNjQzNzM5NjQ0LCJleHAiOjE2NDM3NDE0NDR9.H7iT5ibzm_tkz4bAJ9vJlbvfbOacxMotOBRuRxzYYdU

{
  "username": "albinsuperadmin"
}

###

DELETE http://localhost:5000/users/61f96a671f30f2f5d667d97d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY5NjlhZTFmMzBmMmY1ZDY2N2Q5NzQiLCJ1c2VybmFtZSI6ImFsYmluc3VwZXJhZG1pbjIiLCJlbWFpbCI6ImFsYmluc3VwZXJhZG1pbjJAZ21haWwuY29tIiwicm9sZSI6InN1cGVyYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIyLTAyLTAxVDE3OjExOjEwLjE4OFoiLCJpYXQiOjE2NDM3Mzg5NDksImV4cCI6MTY0Mzc0MDc0OX0.nVStyI1DsrsS-EHmFrztJoMqfx3_9pgxHDP3v2GhZ4U

###

POST http://localhost:5000/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY5NjlhZTFmMzBmMmY1ZDY2N2Q5NzQiLCJ1c2VybmFtZSI6ImFsYmluc3VwZXJhZG1pbjIiLCJlbWFpbCI6ImFsYmluc3VwZXJhZG1pbjJAZ21haWwuY29tIiwicm9sZSI6InN1cGVyYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIyLTAyLTAxVDE3OjExOjEwLjE4OFoiLCJpYXQiOjE2NDM3Mzg5NDksImV4cCI6MTY0Mzc0MDc0OX0.nVStyI1DsrsS-EHmFrztJoMqfx3_9pgxHDP3v2GhZ4U

{
  "username": "albinsuperadmin",
  "email": "albinsuperadmin@gmail.com",
  "password": "abc123",
  "role": "superadmin"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
  "username": "albinsuperadmin",
  "password": "abc123"
}