GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY2ODRhMzdlMzVkMTdiYTUwOTc2ZTYiLCJ1c2VybmFtZSI6ImFsYmluYWRtaW4iLCJlbWFpbCI6ImFsYmluYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyMi0wMS0zMFQxMjoyOToyMy4yNjFaIiwiaWF0IjoxNjQzNzM3NDI2LCJleHAiOjE2NDM3MzkyMjZ9.R6rtjUAYdR96oKgwrOuVPblTrOvhvXrUD2mDcjfgs1A

###

GET http://localhost:5000/users/61f684a37e35d17ba50976e6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY2ODRjMDdlMzVkMTdiYTUwOTc2ZWIiLCJ1c2VybmFtZSI6ImFsYmluc3VwZXJhZG1pbiIsImVtYWlsIjoiYWxiaW5zdXBlcmFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJzdXBlcmFkbWluIiwiY3JlYXRlZEF0IjoiMjAyMi0wMS0zMFQxMjoyOTo1Mi4yMDVaIiwiaWF0IjoxNjQzNzMwNzg2LCJleHAiOjE2NDM3MzI1ODZ9.lp6xA-KZq60uEdfwd-GQS5-NPGXUrkcTNb8rZUDRM-8

###

PATCH http://localhost:5000/users/61f558775eb34c863c800eb6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiYmUyIiwiZW1haWwiOiJhbGJpbjJAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMi0wMS0yOVQxNTowODozOS44MjRaIiwiaWF0IjoxNjQzNTM5NTEyLCJleHAiOjE2NDM1NDEzMTJ9.UxP_DgHwwyqMVns4WvpVmlLrL38Og708GtMDBknZiD8


###

DELETE http://localhost:5000/users/61f969811f30f2f5d667d971
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY2ODRhMzdlMzVkMTdiYTUwOTc2ZTYiLCJ1c2VybmFtZSI6ImFsYmluYWRtaW4iLCJlbWFpbCI6ImFsYmluYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyMi0wMS0zMFQxMjoyOToyMy4yNjFaIiwiaWF0IjoxNjQzNzM3NDI2LCJleHAiOjE2NDM3MzkyMjZ9.R6rtjUAYdR96oKgwrOuVPblTrOvhvXrUD2mDcjfgs1A

###

POST http://localhost:5000/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY2ODRhMzdlMzVkMTdiYTUwOTc2ZTYiLCJ1c2VybmFtZSI6ImFsYmluYWRtaW4iLCJlbWFpbCI6ImFsYmluYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyMi0wMS0zMFQxMjoyOToyMy4yNjFaIiwiaWF0IjoxNjQzNzM1NTk5LCJleHAiOjE2NDM3MzczOTl9.2BRpxTk4nkzz7LRdWe_67Wn-t-DUo1_Dk1-lSMoYlSk

{
  "username": "albinadmin85",
  "email": "albinadmin85@gmail.com",
  "password": "abc123",
  "role": "admin"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
  "username": "albinadmin",
  "password": "abc123"
}